---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuard
  annotations:
    origin/manifest-path: hpa/kuard.yml
    kubernetes.io/change-cause: Initial apply
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kuard
  template:
    metadata:
      annotations:
        origin/manifest-path: hpa/kuard.yml
        kubernetes.io/change-cause: Initial apply
      labels:
        app: kuard
    spec:
      containers:
      - name: kuard
        image: gcr.io/kuar-demo/kuard-amd64:1
        livenessProbe:
          httpGet:
            path: /healthy
            port: 8080
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            memory: 200Mi
            cpu: "0.2"
          requests:
            memory: 100Mi
            cpu: "0.1"
---
apiVersion: v1
kind: Service
metadata:
  name: kuard
  annotations:
    origin/manifest-path: hpa/kuard.yml
    kubernetes.io/change-cause: Initial apply
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: kuard
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kuard
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    origin/manifest-path: hpa/kuard.yml
    kubernetes.io/change-cause: Initial apply
spec:
  ingressClassName: nginx
  rules:
  - host: kuard.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kuard
            port:
              number: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: kuard
  annotations:
    origin/manifest-path: hpa/kuard.yml
    kubernetes.io/change-cause: Initial apply
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kuard
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
