---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuard
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kuard
  template:
    metadata:
      labels:
        app: kuard
    spec:
      containers:
      - name: kuard
        image: gcr.io/kuar-demo/kuard-amd64:1
        livenessProbe:
          httpGet:
            path: /healthy
            port: 8080
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 1
          periodSeconds: 1
          timeoutSeconds: 1
          failureThreshold: 3
          successThreshold: 1
        ports:
        - containerPort: 8080
          protocol: TCP
        command:
          - "/kuard"
          - "$(PARAM1)"
        env:
          - name: PARAM1
            valueFrom:
              configMapKeyRef:
                name: test-config
                key: param1
          - name: PARAM2
            valueFrom:
              configMapKeyRef:
                name: test-config
                key: param2
        volumeMounts:
          - name: config-volume
            mountPath: /config
      volumes:
        - name: config-volume
          configMap:
            name: test-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-config
data:
  param1: hello-world-again
  param2: the-answer-is-42
  config.yml: |
    # A complete config file
    param3: more-config
    param4: some-more
---
apiVersion: v1
kind: Service
metadata:
  name: kuard
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: kuard
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kuard
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    origin/manifest-path: config/kuard.yml
    kubernetes.io/change-cause: Initial apply
spec:
  ingressClassName: nginx
  rules:
  - host: kuard.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kuard
            port:
              number: 8080
