---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuard
  annotations:
    origin/manifest-path: base/kuard.yml
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kuard
  template:
    metadata:
      annotations:
        origin/manifest-path: base/kuard.yml
      labels:
        app: kuard
    spec:
      containers:
      - name: kuard
        image: gcr.io/kuar-demo/kuard-amd64:1
        livenessProbe:
          httpGet:
            path: /healthy
            port: 8080
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 1
          periodSeconds: 1
          timeoutSeconds: 1
          failureThreshold: 3
          successThreshold: 1
        ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: kuard
  annotations:
    origin/manifest-path: base/kuard.yml
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: kuard
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kuard
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    origin/manifest-path: base/kuard.yml
spec:
  ingressClassName: nginx
  rules:
  - host: kuard.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kuard
            port:
              number: 8080
